# Application Configuration
spring.application.name=Api-GateWay-PI
server.port=8090

# Eureka Client Configuration
eureka.client.service-url.defaultZone=http://localhost:8761/eureka
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

# Spring Cloud Gateway Configuration for Route Discovery
spring.cloud.gateway.mvc.routes[0].id=PiProject
spring.cloud.gateway.mvc.routes[0].uri=lb://PiProject
spring.cloud.gateway.mvc.routes[0].predicates[0]=Path=/piproj/offers/**,/piproj/Comment/**,/piproj/Application/**

# Enable automatic route discovery from Eureka
spring.cloud.gateway.discovery.locator.enabled=true
spring.cloud.gateway.discovery.locator.lower-case-service-id=true

# Logging Configuration for Debugging
logging.level.org.springframework.cloud.gateway=DEBUG
logging.level.reactor.netty.http.client=DEBUG
management.endpoints.web.exposure.include=*
logging.level.org.springframework.web=DEBUG
logging.level.reactor.netty=DEBUG
management.endpoint.health.show-details=always
management.endpoint.gateway.enabled=true
